Use File::Spec for MSWin32 on Content-Disposition filename
libwww-perl/HTTP-Message pull request #157
Opened 2021-05-14 23:07 UTC by tzccinct

After HTTP-Message 6.31 (#156), t/common-req.t fails on MSWin32.

```
# Content-Disposition: form-data; name="file"; filename="C:\\Users\\tzccinct\\AppData\\Local\\Temp\\NC6RpG5aiZ"
# Content-Type: text/plain
#
# foo
# bar
# baz
#
#
ok 43
ok 44
ok 45
ok 46
not ok 47
```
https://github.com/libwww-perl/HTTP-Message/blob/161ef4be44b581419f09f38e7a9df4ac598abfdc/t/common-req.t#L157

On other UNIX-like platforms, $form_file is not full path but file name only. To do the same behavior and fix the test failure, I have used File::Spec in this pull request. But this is only for MSWin32 and needs to add File::Spec as runtime prereqs (currently it is test prereqs).

2021-05-17 21:52 UTC, oalders requested changes
Thanks very much for this @tzccinct! Could you add the following to the `Changes` file?

`    - Use File::Spec for MSWin32 on Content-Disposition filename (GH#157) (tzccinct)`

That should fix the builds. 🎉

2021-05-18 11:13 UTC, tzccinct commented
Thanks, I have updated Changes.

2021-05-18 14:16 UTC, oalders approved these changes
👍

2021-05-18 14:16 UTC, merged

2021-05-18 18:55 UTC, oalders commented
Released to CPAN.

2021-05-18 19:00 UTC, Grinnz commented
This isn't really correct in the general case (not that it was before either). File::Spec only knows what the local OS is, it doesn't know the OS of the machine that formed the filename. Instead I think the test should only use the basename and not the filepath as the filename attribute.

2021-05-18 19:09 UTC, Grinnz commented
I might have misinterpreted, this seems to be for *forming* a form request rather than parsing one. In that case the local filepath parsing is appropriate, so disregard my comment.